from pydantic import BaseModel

class promote(BaseModel):
    gender: float
    no_of_trainings: float
    age: float
    previous_year_rating: float
    length_of_service: float
    KPIs_met: float
    awards_won: float
    avg_training_score: float
    department_Analytics: float
    department_Finance: float
    department_HR: float
    department_Legal: float
    department_Operations: float
    department_Procurement: float
    department_RD: float
    department_Sales_Marketing: float
    department_Technology: float
    region_region_1: float
    region_region_10: float
    region_region_11: float
    region_region_12: float
    region_region_13: float
    region_region_14: float
    region_region_15: float
    region_region_16: float
    region_region_17: float
    region_region_18: float
    region_region_19: float
    region_region_2: float
    region_region_20: float
    region_region_21: float 
    region_region_22: float
    region_region_23: float
    region_region_24: float
    region_region_25: float
    region_region_26: float
    region_region_27: float
    region_region_28: float
    region_region_29: float
    region_region_3: float
    region_region_30: float
    region_region_31: float
    region_region_32: float
    region_region_33: float
    region_region_34: float
    region_region_4: float
    region_region_5: float
    region_region_6: float
    region_region_7: float
    region_region_8: float
    region_region_9: float
    education_Bachelor: float
    education_Below_Secondary: float
    education_Master: float
    recruitment_channel_other: float
    recruitment_channel_referred: float
    recruitment_channel_sourcing: float